baseURL = 'https://blog.intron014.com'
languageCode = 'en-us'
title = 'Intron014'
theme = 'Archie'
copyright = '© Intron014'

paginate = 3

[params]
	mode="auto" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "A thorough look into Jorge's brain and life"
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support

    [params.contact]
        email = 'info@example.org'
        phone = '+1 202-555-1212'

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/intron014"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/intron014/"


[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4


